# Site
title: UK Stand-Up
description: Reviews, news and picks from the Edinburgh Fringe and beyond.
url: https://standup.co.uk
baseurl: ""
lang: en-GB
timezone: Europe/London

# URLs
permalink: /:year/:month/:day/:title/

# Theme (robust, accessible, SEO-friendly)
remote_theme: mmistakes/minimal-mistakes@4.26.1
# theme: null  # keep null when using remote_theme

# Minimal Mistakes basics
minimal_mistakes_skin: "default"    # try "air", "contrast", "dark" etc.
logo: /assets/images/site-logo.png  # supply a 1200x630 image for social shares
repository: davorg/standup.co.uk    # your repo (for github-metadata)

# Plugins (great on GitHub Pages when you build via Actions)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-include-cache

# Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 10
  title: ":title — page :num"
  trail:
    before: 2
    after: 2
  permalink: "/page/:num/"

# Archives (nice tag/category pages)
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
    year: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/
    year: /:year/

# Defaults for posts (less front matter to type)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: "UK Stand-Up"
      read_time: true
      comments: false
      share: true
      related: true
      classes: wide
      header:
        overlay_image: /assets/images/social-default.jpg   # 1200x630 recommended
        overlay_filter: 0.4

# Navigation (appears in header)
# Create _data/navigation.yml for richer menus if you like.
# For quick wins:
nav:
  - title: Home
    url: /
  - title: Reviews
    url: /category/reviews/
  - title: News
    url: /category/news/
  - title: Picks
    url: /category/picks/
  - title: About
    url: /about/

# Social + Analytics
social:
  name: UK Stand-Up
  links:
    - https://x.com/yourhandle
    - https://instagram.com/yourhandle
    - https://bsky.app/profile/yourhandle.bsky.social

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-9B2DNH3X51"
    anonymize_ip: true

# Markdown + Sass
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed

# Build hygiene
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json

strict_front_matter: true

