url: https://standup.co.uk/
title: UK Stand-Up
permalink: /:year/:month/:day/:title/index.html

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: "G-9B2DNH3X51"
